//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ControleComissoes
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class controle_comissoesEntities1 : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto controle_comissoesEntities1 usando a cadeia de conexão localizada na seção 'controle_comissoesEntities1' do arquivo de configuração do aplicativo.
        /// </summary>
        public controle_comissoesEntities1() : base("name=controle_comissoesEntities1", "controle_comissoesEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto controle_comissoesEntities1.
        /// </summary>
        public controle_comissoesEntities1(string connectionString) : base(connectionString, "controle_comissoesEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto controle_comissoesEntities1.
        /// </summary>
        public controle_comissoesEntities1(EntityConnection connection) : base(connection, "controle_comissoesEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<cliente_pf> cliente_pf
        {
            get
            {
                if ((_cliente_pf == null))
                {
                    _cliente_pf = base.CreateObjectSet<cliente_pf>("cliente_pf");
                }
                return _cliente_pf;
            }
        }
        private ObjectSet<cliente_pf> _cliente_pf;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet cliente_pf. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTocliente_pf(cliente_pf cliente_pf)
        {
            base.AddObject("cliente_pf", cliente_pf);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="controle_comissoesModel1", Name="cliente_pf")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente_pf : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto cliente_pf.
        /// </summary>
        /// <param name="codigo_pf">Valor inicial da propriedade codigo_pf.</param>
        public static cliente_pf Createcliente_pf(global::System.Int32 codigo_pf)
        {
            cliente_pf cliente_pf = new cliente_pf();
            cliente_pf.codigo_pf = codigo_pf;
            return cliente_pf;
        }

        #endregion

        #region Propriedades Primitivas
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo_pf
        {
            get
            {
                return _codigo_pf;
            }
            set
            {
                if (_codigo_pf != value)
                {
                    Oncodigo_pfChanging(value);
                    ReportPropertyChanging("codigo_pf");
                    _codigo_pf = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo_pf");
                    Oncodigo_pfChanged();
                }
            }
        }
        private global::System.Int32 _codigo_pf;
        partial void Oncodigo_pfChanging(global::System.Int32 value);
        partial void Oncodigo_pfChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cpf
        {
            get
            {
                return _cpf;
            }
            set
            {
                OncpfChanging(value);
                ReportPropertyChanging("cpf");
                _cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cpf");
                OncpfChanged();
            }
        }
        private global::System.String _cpf;
        partial void OncpfChanging(global::System.String value);
        partial void OncpfChanged();

        #endregion

    
    }

    #endregion

    
}
