//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.veiculo = new HashSet<veiculo>();
        }
    
        public int idCliente { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string Celular { get; set; }
        public string email { get; set; }
        public string endereco { get; set; }
        public string situacao { get; set; }
        public Nullable<System.DateTime> primeiroVencimento { get; set; }
        public string tipoCliente { get; set; }
        public Nullable<int> mesesPagos { get; set; }
    
        public virtual ICollection<veiculo> veiculo { get; set; }
        public virtual dependente dependente { get; set; }
        public virtual dependente dependente1 { get; set; }
    }
}
