//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class controle_registro
    {
        public int idControle_Registro { get; set; }
        public Nullable<System.DateTime> dataHoraEntrada { get; set; }
        public Nullable<System.DateTime> dataHoraSaida { get; set; }
        public Nullable<int> idVeiculo { get; set; }
        public Nullable<float> valor { get; set; }
    }
}
