//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estacionamentoEntities : DbContext
    {
        public estacionamentoEntities()
            : base("name=estacionamentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<controle_registro> controle_registro { get; set; }
        public DbSet<dependente> dependente { get; set; }
        public DbSet<tipo_estacionamento> tipo_estacionamento { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<vaga> vaga { get; set; }
        public DbSet<veiculo> veiculo { get; set; }
    }
}
