//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_estacionamento
    {
        public tipo_estacionamento()
        {
            this.veiculo = new HashSet<veiculo>();
        }
    
        public int idTipoEstacionamento { get; set; }
        public string descricao { get; set; }
        public Nullable<float> valor { get; set; }
    
        public virtual ICollection<veiculo> veiculo { get; set; }
    }
}
