//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaga
    {
        public int idVaga { get; set; }
        public string andar { get; set; }
        public string corredor { get; set; }
        public string coluna { get; set; }
        public string vaga1 { get; set; }
        public string situacao { get; set; }
    }
}
