//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("estrelaoriental3Model", "id_Cliente", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Estacionamento.cliente), "gerenciar_situacao_pagamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Estacionamento.gerenciar_situacao_pagamento), true)]
[assembly: EdmRelationshipAttribute("estrelaoriental3Model", "idCliente", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Estacionamento.cliente), "veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Estacionamento.veiculo), true)]
[assembly: EdmRelationshipAttribute("estrelaoriental3Model", "idControleEstacionamento", "controle_estacionar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Estacionamento.controle_estacionar), "preco", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Estacionamento.preco), true)]
[assembly: EdmRelationshipAttribute("estrelaoriental3Model", "idGerenciarSituacaoPagamento", "gerenciar_situacao_pagamento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Estacionamento.gerenciar_situacao_pagamento), "controle_estacionar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Estacionamento.controle_estacionar), true)]
[assembly: EdmRelationshipAttribute("estrelaoriental3Model", "id_Veiculo", "veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Estacionamento.veiculo), "gerenciar_situacao_pagamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Estacionamento.gerenciar_situacao_pagamento), true)]
[assembly: EdmRelationshipAttribute("estrelaoriental3Model", "idTipoPlanoEstacionamento", "tipo_plano_estacionamento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Estacionamento.tipo_plano_estacionamento), "gerenciar_situacao_pagamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Estacionamento.gerenciar_situacao_pagamento), true)]

#endregion

namespace Estacionamento
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class estrelaoriental3Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new estrelaoriental3Entities1 object using the connection string found in the 'estrelaoriental3Entities1' section of the application configuration file.
        /// </summary>
        public estrelaoriental3Entities1() : base("name=estrelaoriental3Entities1", "estrelaoriental3Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new estrelaoriental3Entities1 object.
        /// </summary>
        public estrelaoriental3Entities1(string connectionString) : base(connectionString, "estrelaoriental3Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new estrelaoriental3Entities1 object.
        /// </summary>
        public estrelaoriental3Entities1(EntityConnection connection) : base(connection, "estrelaoriental3Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cliente> cliente
        {
            get
            {
                if ((_cliente == null))
                {
                    _cliente = base.CreateObjectSet<cliente>("cliente");
                }
                return _cliente;
            }
        }
        private ObjectSet<cliente> _cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<controle_estacionar> controle_estacionar
        {
            get
            {
                if ((_controle_estacionar == null))
                {
                    _controle_estacionar = base.CreateObjectSet<controle_estacionar>("controle_estacionar");
                }
                return _controle_estacionar;
            }
        }
        private ObjectSet<controle_estacionar> _controle_estacionar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gerenciar_situacao_pagamento> gerenciar_situacao_pagamento
        {
            get
            {
                if ((_gerenciar_situacao_pagamento == null))
                {
                    _gerenciar_situacao_pagamento = base.CreateObjectSet<gerenciar_situacao_pagamento>("gerenciar_situacao_pagamento");
                }
                return _gerenciar_situacao_pagamento;
            }
        }
        private ObjectSet<gerenciar_situacao_pagamento> _gerenciar_situacao_pagamento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<preco> preco
        {
            get
            {
                if ((_preco == null))
                {
                    _preco = base.CreateObjectSet<preco>("preco");
                }
                return _preco;
            }
        }
        private ObjectSet<preco> _preco;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tipo_plano_estacionamento> tipo_plano_estacionamento
        {
            get
            {
                if ((_tipo_plano_estacionamento == null))
                {
                    _tipo_plano_estacionamento = base.CreateObjectSet<tipo_plano_estacionamento>("tipo_plano_estacionamento");
                }
                return _tipo_plano_estacionamento;
            }
        }
        private ObjectSet<tipo_plano_estacionamento> _tipo_plano_estacionamento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuario
        {
            get
            {
                if ((_usuario == null))
                {
                    _usuario = base.CreateObjectSet<usuario>("usuario");
                }
                return _usuario;
            }
        }
        private ObjectSet<usuario> _usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vaga> vaga
        {
            get
            {
                if ((_vaga == null))
                {
                    _vaga = base.CreateObjectSet<vaga>("vaga");
                }
                return _vaga;
            }
        }
        private ObjectSet<vaga> _vaga;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<veiculo> veiculo
        {
            get
            {
                if ((_veiculo == null))
                {
                    _veiculo = base.CreateObjectSet<veiculo>("veiculo");
                }
                return _veiculo;
            }
        }
        private ObjectSet<veiculo> _veiculo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocliente(cliente cliente)
        {
            base.AddObject("cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the controle_estacionar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocontrole_estacionar(controle_estacionar controle_estacionar)
        {
            base.AddObject("controle_estacionar", controle_estacionar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gerenciar_situacao_pagamento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogerenciar_situacao_pagamento(gerenciar_situacao_pagamento gerenciar_situacao_pagamento)
        {
            base.AddObject("gerenciar_situacao_pagamento", gerenciar_situacao_pagamento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the preco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopreco(preco preco)
        {
            base.AddObject("preco", preco);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tipo_plano_estacionamento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotipo_plano_estacionamento(tipo_plano_estacionamento tipo_plano_estacionamento)
        {
            base.AddObject("tipo_plano_estacionamento", tipo_plano_estacionamento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario(usuario usuario)
        {
            base.AddObject("usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vaga EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovaga(vaga vaga)
        {
            base.AddObject("vaga", vaga);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the veiculo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToveiculo(veiculo veiculo)
        {
            base.AddObject("veiculo", veiculo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        public static cliente Createcliente(global::System.Int32 idCliente)
        {
            cliente cliente = new cliente();
            cliente.idCliente = idCliente;
            return cliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                if (_idCliente != value)
                {
                    OnidClienteChanging(value);
                    ReportPropertyChanging("idCliente");
                    _idCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCliente");
                    OnidClienteChanged();
                }
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipoCliente
        {
            get
            {
                return _tipoCliente;
            }
            set
            {
                OntipoClienteChanging(value);
                ReportPropertyChanging("tipoCliente");
                _tipoCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipoCliente");
                OntipoClienteChanged();
            }
        }
        private global::System.String _tipoCliente;
        partial void OntipoClienteChanging(global::System.String value);
        partial void OntipoClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "id_Cliente", "gerenciar_situacao_pagamento")]
        public EntityCollection<gerenciar_situacao_pagamento> gerenciar_situacao_pagamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gerenciar_situacao_pagamento>("estrelaoriental3Model.id_Cliente", "gerenciar_situacao_pagamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gerenciar_situacao_pagamento>("estrelaoriental3Model.id_Cliente", "gerenciar_situacao_pagamento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idCliente", "veiculo")]
        public EntityCollection<veiculo> veiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<veiculo>("estrelaoriental3Model.idCliente", "veiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<veiculo>("estrelaoriental3Model.idCliente", "veiculo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="controle_estacionar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class controle_estacionar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new controle_estacionar object.
        /// </summary>
        /// <param name="idControle_Registro">Initial value of the idControle_Registro property.</param>
        public static controle_estacionar Createcontrole_estacionar(global::System.Int32 idControle_Registro)
        {
            controle_estacionar controle_estacionar = new controle_estacionar();
            controle_estacionar.idControle_Registro = idControle_Registro;
            return controle_estacionar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idControle_Registro
        {
            get
            {
                return _idControle_Registro;
            }
            set
            {
                if (_idControle_Registro != value)
                {
                    OnidControle_RegistroChanging(value);
                    ReportPropertyChanging("idControle_Registro");
                    _idControle_Registro = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idControle_Registro");
                    OnidControle_RegistroChanged();
                }
            }
        }
        private global::System.Int32 _idControle_Registro;
        partial void OnidControle_RegistroChanging(global::System.Int32 value);
        partial void OnidControle_RegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataHoraEntrada
        {
            get
            {
                return _dataHoraEntrada;
            }
            set
            {
                OndataHoraEntradaChanging(value);
                ReportPropertyChanging("dataHoraEntrada");
                _dataHoraEntrada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataHoraEntrada");
                OndataHoraEntradaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataHoraEntrada;
        partial void OndataHoraEntradaChanging(Nullable<global::System.DateTime> value);
        partial void OndataHoraEntradaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataHoraSaida
        {
            get
            {
                return _dataHoraSaida;
            }
            set
            {
                OndataHoraSaidaChanging(value);
                ReportPropertyChanging("dataHoraSaida");
                _dataHoraSaida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataHoraSaida");
                OndataHoraSaidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataHoraSaida;
        partial void OndataHoraSaidaChanging(Nullable<global::System.DateTime> value);
        partial void OndataHoraSaidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Single> _valor;
        partial void OnvalorChanging(Nullable<global::System.Single> value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idVaga
        {
            get
            {
                return _idVaga;
            }
            set
            {
                OnidVagaChanging(value);
                ReportPropertyChanging("idVaga");
                _idVaga = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idVaga");
                OnidVagaChanged();
            }
        }
        private Nullable<global::System.Int32> _idVaga;
        partial void OnidVagaChanging(Nullable<global::System.Int32> value);
        partial void OnidVagaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idGerenciarSituacaoPagamento
        {
            get
            {
                return _idGerenciarSituacaoPagamento;
            }
            set
            {
                OnidGerenciarSituacaoPagamentoChanging(value);
                ReportPropertyChanging("idGerenciarSituacaoPagamento");
                _idGerenciarSituacaoPagamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idGerenciarSituacaoPagamento");
                OnidGerenciarSituacaoPagamentoChanged();
            }
        }
        private Nullable<global::System.Int32> _idGerenciarSituacaoPagamento;
        partial void OnidGerenciarSituacaoPagamentoChanging(Nullable<global::System.Int32> value);
        partial void OnidGerenciarSituacaoPagamentoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idControleEstacionamento", "preco")]
        public EntityCollection<preco> preco
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<preco>("estrelaoriental3Model.idControleEstacionamento", "preco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<preco>("estrelaoriental3Model.idControleEstacionamento", "preco", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idGerenciarSituacaoPagamento", "gerenciar_situacao_pagamento")]
        public gerenciar_situacao_pagamento gerenciar_situacao_pagamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gerenciar_situacao_pagamento>("estrelaoriental3Model.idGerenciarSituacaoPagamento", "gerenciar_situacao_pagamento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gerenciar_situacao_pagamento>("estrelaoriental3Model.idGerenciarSituacaoPagamento", "gerenciar_situacao_pagamento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gerenciar_situacao_pagamento> gerenciar_situacao_pagamentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gerenciar_situacao_pagamento>("estrelaoriental3Model.idGerenciarSituacaoPagamento", "gerenciar_situacao_pagamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gerenciar_situacao_pagamento>("estrelaoriental3Model.idGerenciarSituacaoPagamento", "gerenciar_situacao_pagamento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="gerenciar_situacao_pagamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gerenciar_situacao_pagamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gerenciar_situacao_pagamento object.
        /// </summary>
        /// <param name="idGerenciarSituacaoPagamento">Initial value of the idGerenciarSituacaoPagamento property.</param>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        /// <param name="idVeiculo">Initial value of the idVeiculo property.</param>
        /// <param name="idTipoPlanoEstacionamento">Initial value of the idTipoPlanoEstacionamento property.</param>
        public static gerenciar_situacao_pagamento Creategerenciar_situacao_pagamento(global::System.Int32 idGerenciarSituacaoPagamento, global::System.Int32 idCliente, global::System.Int32 idVeiculo, global::System.Int32 idTipoPlanoEstacionamento)
        {
            gerenciar_situacao_pagamento gerenciar_situacao_pagamento = new gerenciar_situacao_pagamento();
            gerenciar_situacao_pagamento.idGerenciarSituacaoPagamento = idGerenciarSituacaoPagamento;
            gerenciar_situacao_pagamento.idCliente = idCliente;
            gerenciar_situacao_pagamento.idVeiculo = idVeiculo;
            gerenciar_situacao_pagamento.idTipoPlanoEstacionamento = idTipoPlanoEstacionamento;
            return gerenciar_situacao_pagamento;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idGerenciarSituacaoPagamento
        {
            get
            {
                return _idGerenciarSituacaoPagamento;
            }
            set
            {
                if (_idGerenciarSituacaoPagamento != value)
                {
                    OnidGerenciarSituacaoPagamentoChanging(value);
                    ReportPropertyChanging("idGerenciarSituacaoPagamento");
                    _idGerenciarSituacaoPagamento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idGerenciarSituacaoPagamento");
                    OnidGerenciarSituacaoPagamentoChanged();
                }
            }
        }
        private global::System.Int32 _idGerenciarSituacaoPagamento;
        partial void OnidGerenciarSituacaoPagamentoChanging(global::System.Int32 value);
        partial void OnidGerenciarSituacaoPagamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                OnidClienteChanging(value);
                ReportPropertyChanging("idCliente");
                _idCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCliente");
                OnidClienteChanged();
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idVeiculo
        {
            get
            {
                return _idVeiculo;
            }
            set
            {
                OnidVeiculoChanging(value);
                ReportPropertyChanging("idVeiculo");
                _idVeiculo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idVeiculo");
                OnidVeiculoChanged();
            }
        }
        private global::System.Int32 _idVeiculo;
        partial void OnidVeiculoChanging(global::System.Int32 value);
        partial void OnidVeiculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoPlanoEstacionamento
        {
            get
            {
                return _idTipoPlanoEstacionamento;
            }
            set
            {
                OnidTipoPlanoEstacionamentoChanging(value);
                ReportPropertyChanging("idTipoPlanoEstacionamento");
                _idTipoPlanoEstacionamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTipoPlanoEstacionamento");
                OnidTipoPlanoEstacionamentoChanged();
            }
        }
        private global::System.Int32 _idTipoPlanoEstacionamento;
        partial void OnidTipoPlanoEstacionamentoChanging(global::System.Int32 value);
        partial void OnidTipoPlanoEstacionamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String situacaoPagamento
        {
            get
            {
                return _situacaoPagamento;
            }
            set
            {
                OnsituacaoPagamentoChanging(value);
                ReportPropertyChanging("situacaoPagamento");
                _situacaoPagamento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("situacaoPagamento");
                OnsituacaoPagamentoChanged();
            }
        }
        private global::System.String _situacaoPagamento;
        partial void OnsituacaoPagamentoChanging(global::System.String value);
        partial void OnsituacaoPagamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> vencimentoPagamento
        {
            get
            {
                return _vencimentoPagamento;
            }
            set
            {
                OnvencimentoPagamentoChanging(value);
                ReportPropertyChanging("vencimentoPagamento");
                _vencimentoPagamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vencimentoPagamento");
                OnvencimentoPagamentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _vencimentoPagamento;
        partial void OnvencimentoPagamentoChanging(Nullable<global::System.DateTime> value);
        partial void OnvencimentoPagamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mesesPagos
        {
            get
            {
                return _mesesPagos;
            }
            set
            {
                OnmesesPagosChanging(value);
                ReportPropertyChanging("mesesPagos");
                _mesesPagos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mesesPagos");
                OnmesesPagosChanged();
            }
        }
        private Nullable<global::System.Int32> _mesesPagos;
        partial void OnmesesPagosChanging(Nullable<global::System.Int32> value);
        partial void OnmesesPagosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "id_Cliente", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("estrelaoriental3Model.id_Cliente", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("estrelaoriental3Model.id_Cliente", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("estrelaoriental3Model.id_Cliente", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("estrelaoriental3Model.id_Cliente", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idGerenciarSituacaoPagamento", "controle_estacionar")]
        public EntityCollection<controle_estacionar> controle_estacionar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<controle_estacionar>("estrelaoriental3Model.idGerenciarSituacaoPagamento", "controle_estacionar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<controle_estacionar>("estrelaoriental3Model.idGerenciarSituacaoPagamento", "controle_estacionar", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "id_Veiculo", "veiculo")]
        public veiculo veiculo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<veiculo>("estrelaoriental3Model.id_Veiculo", "veiculo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<veiculo>("estrelaoriental3Model.id_Veiculo", "veiculo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<veiculo> veiculoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<veiculo>("estrelaoriental3Model.id_Veiculo", "veiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<veiculo>("estrelaoriental3Model.id_Veiculo", "veiculo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idTipoPlanoEstacionamento", "tipo_plano_estacionamento")]
        public tipo_plano_estacionamento tipo_plano_estacionamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_plano_estacionamento>("estrelaoriental3Model.idTipoPlanoEstacionamento", "tipo_plano_estacionamento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_plano_estacionamento>("estrelaoriental3Model.idTipoPlanoEstacionamento", "tipo_plano_estacionamento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipo_plano_estacionamento> tipo_plano_estacionamentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_plano_estacionamento>("estrelaoriental3Model.idTipoPlanoEstacionamento", "tipo_plano_estacionamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipo_plano_estacionamento>("estrelaoriental3Model.idTipoPlanoEstacionamento", "tipo_plano_estacionamento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="preco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class preco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new preco object.
        /// </summary>
        /// <param name="idPreco">Initial value of the idPreco property.</param>
        public static preco Createpreco(global::System.Int32 idPreco)
        {
            preco preco = new preco();
            preco.idPreco = idPreco;
            return preco;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPreco
        {
            get
            {
                return _idPreco;
            }
            set
            {
                if (_idPreco != value)
                {
                    OnidPrecoChanging(value);
                    ReportPropertyChanging("idPreco");
                    _idPreco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPreco");
                    OnidPrecoChanged();
                }
            }
        }
        private global::System.Int32 _idPreco;
        partial void OnidPrecoChanging(global::System.Int32 value);
        partial void OnidPrecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Single> _valor;
        partial void OnvalorChanging(Nullable<global::System.Single> value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idControleEstacionamento
        {
            get
            {
                return _idControleEstacionamento;
            }
            set
            {
                OnidControleEstacionamentoChanging(value);
                ReportPropertyChanging("idControleEstacionamento");
                _idControleEstacionamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idControleEstacionamento");
                OnidControleEstacionamentoChanged();
            }
        }
        private Nullable<global::System.Int32> _idControleEstacionamento;
        partial void OnidControleEstacionamentoChanging(Nullable<global::System.Int32> value);
        partial void OnidControleEstacionamentoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idControleEstacionamento", "controle_estacionar")]
        public controle_estacionar controle_estacionar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<controle_estacionar>("estrelaoriental3Model.idControleEstacionamento", "controle_estacionar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<controle_estacionar>("estrelaoriental3Model.idControleEstacionamento", "controle_estacionar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<controle_estacionar> controle_estacionarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<controle_estacionar>("estrelaoriental3Model.idControleEstacionamento", "controle_estacionar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<controle_estacionar>("estrelaoriental3Model.idControleEstacionamento", "controle_estacionar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="tipo_plano_estacionamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo_plano_estacionamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tipo_plano_estacionamento object.
        /// </summary>
        /// <param name="idTipoEstacionamento">Initial value of the idTipoEstacionamento property.</param>
        public static tipo_plano_estacionamento Createtipo_plano_estacionamento(global::System.Int32 idTipoEstacionamento)
        {
            tipo_plano_estacionamento tipo_plano_estacionamento = new tipo_plano_estacionamento();
            tipo_plano_estacionamento.idTipoEstacionamento = idTipoEstacionamento;
            return tipo_plano_estacionamento;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoEstacionamento
        {
            get
            {
                return _idTipoEstacionamento;
            }
            set
            {
                if (_idTipoEstacionamento != value)
                {
                    OnidTipoEstacionamentoChanging(value);
                    ReportPropertyChanging("idTipoEstacionamento");
                    _idTipoEstacionamento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTipoEstacionamento");
                    OnidTipoEstacionamentoChanged();
                }
            }
        }
        private global::System.Int32 _idTipoEstacionamento;
        partial void OnidTipoEstacionamentoChanging(global::System.Int32 value);
        partial void OnidTipoEstacionamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Single> _valor;
        partial void OnvalorChanging(Nullable<global::System.Single> value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mesesPlano
        {
            get
            {
                return _mesesPlano;
            }
            set
            {
                OnmesesPlanoChanging(value);
                ReportPropertyChanging("mesesPlano");
                _mesesPlano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mesesPlano");
                OnmesesPlanoChanged();
            }
        }
        private Nullable<global::System.Int32> _mesesPlano;
        partial void OnmesesPlanoChanging(Nullable<global::System.Int32> value);
        partial void OnmesesPlanoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idTipoPlanoEstacionamento", "gerenciar_situacao_pagamento")]
        public EntityCollection<gerenciar_situacao_pagamento> gerenciar_situacao_pagamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gerenciar_situacao_pagamento>("estrelaoriental3Model.idTipoPlanoEstacionamento", "gerenciar_situacao_pagamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gerenciar_situacao_pagamento>("estrelaoriental3Model.idTipoPlanoEstacionamento", "gerenciar_situacao_pagamento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="idusuario">Initial value of the idusuario property.</param>
        public static usuario Createusuario(global::System.Int32 idusuario)
        {
            usuario usuario = new usuario();
            usuario.idusuario = idusuario;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idusuario
        {
            get
            {
                return _idusuario;
            }
            set
            {
                if (_idusuario != value)
                {
                    OnidusuarioChanging(value);
                    ReportPropertyChanging("idusuario");
                    _idusuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idusuario");
                    OnidusuarioChanged();
                }
            }
        }
        private global::System.Int32 _idusuario;
        partial void OnidusuarioChanging(global::System.Int32 value);
        partial void OnidusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String celular
        {
            get
            {
                return _celular;
            }
            set
            {
                OncelularChanging(value);
                ReportPropertyChanging("celular");
                _celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("celular");
                OncelularChanged();
            }
        }
        private global::System.String _celular;
        partial void OncelularChanging(global::System.String value);
        partial void OncelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipoUsuario
        {
            get
            {
                return _tipoUsuario;
            }
            set
            {
                OntipoUsuarioChanging(value);
                ReportPropertyChanging("tipoUsuario");
                _tipoUsuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipoUsuario");
                OntipoUsuarioChanged();
            }
        }
        private global::System.String _tipoUsuario;
        partial void OntipoUsuarioChanging(global::System.String value);
        partial void OntipoUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="vaga")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vaga : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vaga object.
        /// </summary>
        /// <param name="idVaga">Initial value of the idVaga property.</param>
        public static vaga Createvaga(global::System.Int32 idVaga)
        {
            vaga vaga = new vaga();
            vaga.idVaga = idVaga;
            return vaga;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idVaga
        {
            get
            {
                return _idVaga;
            }
            set
            {
                if (_idVaga != value)
                {
                    OnidVagaChanging(value);
                    ReportPropertyChanging("idVaga");
                    _idVaga = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idVaga");
                    OnidVagaChanged();
                }
            }
        }
        private global::System.Int32 _idVaga;
        partial void OnidVagaChanging(global::System.Int32 value);
        partial void OnidVagaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> andar
        {
            get
            {
                return _andar;
            }
            set
            {
                OnandarChanging(value);
                ReportPropertyChanging("andar");
                _andar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("andar");
                OnandarChanged();
            }
        }
        private Nullable<global::System.Int32> _andar;
        partial void OnandarChanging(Nullable<global::System.Int32> value);
        partial void OnandarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vaga1
        {
            get
            {
                return _vaga1;
            }
            set
            {
                Onvaga1Changing(value);
                ReportPropertyChanging("vaga1");
                _vaga1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vaga1");
                Onvaga1Changed();
            }
        }
        private global::System.String _vaga1;
        partial void Onvaga1Changing(global::System.String value);
        partial void Onvaga1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private Nullable<global::System.Int32> _tipo;
        partial void OntipoChanging(Nullable<global::System.Int32> value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String situacao
        {
            get
            {
                return _situacao;
            }
            set
            {
                OnsituacaoChanging(value);
                ReportPropertyChanging("situacao");
                _situacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("situacao");
                OnsituacaoChanged();
            }
        }
        private global::System.String _situacao;
        partial void OnsituacaoChanging(global::System.String value);
        partial void OnsituacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> posicao_x
        {
            get
            {
                return _posicao_x;
            }
            set
            {
                Onposicao_xChanging(value);
                ReportPropertyChanging("posicao_x");
                _posicao_x = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("posicao_x");
                Onposicao_xChanged();
            }
        }
        private Nullable<global::System.Int32> _posicao_x;
        partial void Onposicao_xChanging(Nullable<global::System.Int32> value);
        partial void Onposicao_xChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> posicao_y
        {
            get
            {
                return _posicao_y;
            }
            set
            {
                Onposicao_yChanging(value);
                ReportPropertyChanging("posicao_y");
                _posicao_y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("posicao_y");
                Onposicao_yChanged();
            }
        }
        private Nullable<global::System.Int32> _posicao_y;
        partial void Onposicao_yChanging(Nullable<global::System.Int32> value);
        partial void Onposicao_yChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> angulo
        {
            get
            {
                return _angulo;
            }
            set
            {
                OnanguloChanging(value);
                ReportPropertyChanging("angulo");
                _angulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("angulo");
                OnanguloChanged();
            }
        }
        private Nullable<global::System.Int32> _angulo;
        partial void OnanguloChanging(Nullable<global::System.Int32> value);
        partial void OnanguloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> remove
        {
            get
            {
                return _remove;
            }
            set
            {
                OnremoveChanging(value);
                ReportPropertyChanging("remove");
                _remove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("remove");
                OnremoveChanged();
            }
        }
        private Nullable<global::System.Int32> _remove;
        partial void OnremoveChanging(Nullable<global::System.Int32> value);
        partial void OnremoveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="estrelaoriental3Model", Name="veiculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class veiculo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new veiculo object.
        /// </summary>
        /// <param name="idVeiculo">Initial value of the idVeiculo property.</param>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        public static veiculo Createveiculo(global::System.Int32 idVeiculo, global::System.Int32 idCliente)
        {
            veiculo veiculo = new veiculo();
            veiculo.idVeiculo = idVeiculo;
            veiculo.idCliente = idCliente;
            return veiculo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idVeiculo
        {
            get
            {
                return _idVeiculo;
            }
            set
            {
                if (_idVeiculo != value)
                {
                    OnidVeiculoChanging(value);
                    ReportPropertyChanging("idVeiculo");
                    _idVeiculo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idVeiculo");
                    OnidVeiculoChanged();
                }
            }
        }
        private global::System.Int32 _idVeiculo;
        partial void OnidVeiculoChanging(global::System.Int32 value);
        partial void OnidVeiculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String placa
        {
            get
            {
                return _placa;
            }
            set
            {
                OnplacaChanging(value);
                ReportPropertyChanging("placa");
                _placa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("placa");
                OnplacaChanged();
            }
        }
        private global::System.String _placa;
        partial void OnplacaChanging(global::System.String value);
        partial void OnplacaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.String _marca;
        partial void OnmarcaChanging(global::System.String value);
        partial void OnmarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modelo
        {
            get
            {
                return _modelo;
            }
            set
            {
                OnmodeloChanging(value);
                ReportPropertyChanging("modelo");
                _modelo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modelo");
                OnmodeloChanged();
            }
        }
        private global::System.String _modelo;
        partial void OnmodeloChanging(global::System.String value);
        partial void OnmodeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ano
        {
            get
            {
                return _ano;
            }
            set
            {
                OnanoChanging(value);
                ReportPropertyChanging("ano");
                _ano = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ano");
                OnanoChanged();
            }
        }
        private global::System.String _ano;
        partial void OnanoChanging(global::System.String value);
        partial void OnanoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                OnidClienteChanging(value);
                ReportPropertyChanging("idCliente");
                _idCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCliente");
                OnidClienteChanged();
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private Nullable<global::System.Int32> _tipo;
        partial void OntipoChanging(Nullable<global::System.Int32> value);
        partial void OntipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "idCliente", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("estrelaoriental3Model.idCliente", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("estrelaoriental3Model.idCliente", "cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("estrelaoriental3Model.idCliente", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("estrelaoriental3Model.idCliente", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("estrelaoriental3Model", "id_Veiculo", "gerenciar_situacao_pagamento")]
        public EntityCollection<gerenciar_situacao_pagamento> gerenciar_situacao_pagamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gerenciar_situacao_pagamento>("estrelaoriental3Model.id_Veiculo", "gerenciar_situacao_pagamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gerenciar_situacao_pagamento>("estrelaoriental3Model.id_Veiculo", "gerenciar_situacao_pagamento", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
